# Generated by Django 6.0.4 on 2026-04-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20260409_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_kepegawaian',
            field=models.CharField(blank=True, choices=[('Aktif', 'Aktif'), ('Tugas Belajar', 'Tugas Belajar'), ('Lanjut Studi', 'Lanjut Studi'), ('Keluar', 'Keluar'), ('Meninggal', 'Meninggal')], default='Aktif', max_length=20, null=True),
        ),
    ]
