# Generated by Django 6.0.4 on 2026-04-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_status_kepegawaian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('rektorat', 'Rektorat'), ('biro', 'Biro/Lembaga'), ('dekan', 'Dekan'), ('wadek', 'Wakil Dekan'), ('kaprodi', 'Ketua Program Studi'), ('sekprodi', 'Sekretaris Prodi'), ('tendik', 'Tendik'), ('dosen', 'Dosen')], default='dosen', max_length=20),
        ),
    ]
