# Generated by Django 6.0.4 on 2026-04-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('nama', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('jenis', models.CharField(choices=[('login_berhasil', 'Login Berhasil'), ('login_gagal', 'Login Gagal'), ('login_nonaktif', 'Login Ditolak (Nonaktif)'), ('captcha_salah', 'CAPTCHA Salah'), ('logout', 'Logout')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('keterangan', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Log Aktivitas',
                'verbose_name_plural': 'Log Aktivitas',
                'ordering': ['-waktu'],
            },
        ),
    ]
