# Generated by Django 6.0.4 on 2026-07-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_logaktivitas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status_kepegawaian',
        ),
    ]
