# Generated by Django 6.0.4 on 2026-04-09 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_fakultas', models.CharField(max_length=10, unique=True)),
                ('nama_fakultas', models.CharField(max_length=100)),
                ('nama_dekan', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=10)),
            ],
            options={
                'verbose_name': 'Fakultas',
                'verbose_name_plural': 'Fakultas',
                'ordering': ['kode_fakultas'],
            },
        ),
        migrations.CreateModel(
            name='Pengaturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_input', models.CharField(choices=[('buka', 'Buka'), ('kunci', 'Kunci')], default='buka', max_length=10)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('ts_label', models.CharField(default='TS', max_length=10)),
                ('ts_tahun', models.CharField(default='2024-2025', max_length=10)),
                ('ts1_label', models.CharField(default='TS-1', max_length=10)),
                ('ts1_tahun', models.CharField(default='2023-2024', max_length=10)),
                ('ts2_label', models.CharField(default='TS-2', max_length=10)),
                ('ts2_tahun', models.CharField(default='2022-2023', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan',
                'verbose_name_plural': 'Pengaturan',
            },
        ),
        migrations.CreateModel(
            name='TahunAkademik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_akademik', models.CharField(max_length=10, unique=True)),
                ('keterangan', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=10)),
                ('urutan', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tahun Akademik',
                'verbose_name_plural': 'Tahun Akademik',
                'ordering': ['-urutan'],
            },
        ),
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(max_length=10, unique=True)),
                ('nama_prodi', models.CharField(max_length=100)),
                ('nama_kaprodi', models.CharField(blank=True, max_length=100, null=True)),
                ('jenjang', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('D3', 'D3'), ('D4', 'D4')], default='S1', max_length=5)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=10)),
                ('fakultas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodi_set', to='master.fakultas')),
            ],
            options={
                'verbose_name': 'Program Studi',
                'verbose_name_plural': 'Program Studi',
                'ordering': ['fakultas__kode_fakultas', 'kode_prodi'],
            },
        ),
    ]
