# Generated by Django 6.0.4 on 2026-08-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaturan',
            name='url_template_garuda',
            field=models.CharField(blank=True, default='https://garuda.kemdikbud.go.id/author/view/{id}', max_length=255),
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='url_template_google_scholar',
            field=models.CharField(blank=True, default='https://scholar.google.com/citations?user={id}', max_length=255),
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='url_template_orcid',
            field=models.CharField(blank=True, default='https://orcid.org/{id}', max_length=255),
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='url_template_scopus',
            field=models.CharField(blank=True, default='https://www.scopus.com/authid/detail.uri?authorId={id}', max_length=255),
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='url_template_sinta',
            field=models.CharField(blank=True, default='https://sinta.kemdiktisaintek.go.id/authors/profile/{id}/?view=garuda', max_length=255),
        ),
    ]
