# Generated by Django 6.0.4 on 2026-07-28 05:19

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolmentWajah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidn', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='NIDN Dosen')),
                ('embedding_terenkripsi', models.BinaryField(verbose_name='Embedding wajah (terenkripsi)')),
                ('versi_model', models.CharField(blank=True, max_length=40)),
                ('consent_disetujui', models.BooleanField(default=False, verbose_name='Persetujuan biometrik (UU PDP)')),
                ('consent_pada', models.DateTimeField(blank=True, null=True)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diperbarui', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enrolment Wajah',
                'verbose_name_plural': 'Enrolment Wajah',
            },
        ),
        migrations.CreateModel(
            name='IzinCuti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidn', models.CharField(db_index=True, max_length=20, verbose_name='NIDN Dosen')),
                ('tipe', models.CharField(choices=[('izin', 'Izin'), ('sakit', 'Sakit'), ('cuti', 'Cuti'), ('dinas', 'Dinas Luar')], max_length=6)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('alasan', models.TextField(blank=True)),
                ('lampiran', models.FileField(blank=True, upload_to='presensi/izin/%Y/%m/')),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='menunggu', max_length=10)),
                ('approver', models.CharField(blank=True, max_length=50, verbose_name='NIDN/ID atasan')),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LokasiKantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150, verbose_name='Nama lokasi')),
                ('latitude', models.FloatField(verbose_name='Latitude titik pusat')),
                ('longitude', models.FloatField(verbose_name='Longitude titik pusat')),
                ('radius_meter', models.PositiveIntegerField(default=100, verbose_name='Radius geofence (meter)')),
                ('jam_masuk', models.TimeField(default=datetime.time(8, 0))),
                ('jam_pulang', models.TimeField(default=datetime.time(16, 0))),
                ('toleransi_menit', models.PositiveIntegerField(default=15, verbose_name='Toleransi telat (menit)')),
                ('timezone', models.CharField(default='Asia/Makassar', max_length=64)),
                ('wajib_qr', models.BooleanField(default=False, verbose_name='Wajibkan scan QR')),
                ('wajib_wifi', models.BooleanField(default=False, verbose_name='Wajibkan Wi-Fi/IP kantor')),
                ('ssid_wifi', models.CharField(blank=True, max_length=100, verbose_name='SSID Wi-Fi kantor')),
                ('ip_jaringan', models.CharField(blank=True, max_length=64, verbose_name='Rentang IP kantor (CIDR)')),
                ('aktif', models.BooleanField(default=True)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lokasi Kantor',
                'verbose_name_plural': 'Lokasi Kantor',
            },
        ),
        migrations.CreateModel(
            name='JadwalKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidn', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='NIDN Dosen')),
                ('hari', models.PositiveSmallIntegerField(default=0, verbose_name='Hari (0=Senin..6=Minggu)')),
                ('jam_masuk', models.TimeField(default=datetime.time(8, 0))),
                ('jam_pulang', models.TimeField(default=datetime.time(16, 0))),
                ('aktif', models.BooleanField(default=True)),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jadwal', to='presensi.lokasikantor')),
            ],
            options={
                'verbose_name': 'Jadwal Kerja',
                'verbose_name_plural': 'Jadwal Kerja',
            },
        ),
        migrations.CreateModel(
            name='Perangkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidn', models.CharField(db_index=True, max_length=20, verbose_name='NIDN Dosen')),
                ('device_id', models.CharField(max_length=200, verbose_name='ID perangkat')),
                ('platform', models.CharField(blank=True, max_length=40)),
                ('terpercaya', models.BooleanField(default=False, verbose_name='Disetujui admin')),
                ('is_rooted', models.BooleanField(default=False, verbose_name='Terdeteksi root/emulator')),
                ('terakhir_dipakai', models.DateTimeField(blank=True, null=True)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Perangkat',
                'verbose_name_plural': 'Perangkat',
                'unique_together': {('nidn', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidn', models.CharField(db_index=True, max_length=20, verbose_name='NIDN Dosen')),
                ('tanggal', models.DateField(default=django.utils.timezone.localdate)),
                ('waktu_masuk', models.DateTimeField(blank=True, null=True)),
                ('waktu_pulang', models.DateTimeField(blank=True, null=True)),
                ('latitude_masuk', models.FloatField(blank=True, null=True)),
                ('longitude_masuk', models.FloatField(blank=True, null=True)),
                ('latitude_pulang', models.FloatField(blank=True, null=True)),
                ('longitude_pulang', models.FloatField(blank=True, null=True)),
                ('akurasi_masuk_m', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('telat', 'Terlambat'), ('izin', 'Izin/Cuti'), ('alpa', 'Alpa'), ('ditolak', 'Ditolak (anomali)')], default='hadir', max_length=10)),
                ('skor_risiko', models.PositiveSmallIntegerField(default=0)),
                ('tingkat_risiko', models.CharField(choices=[('rendah', 'Rendah — otomatis sah'), ('sedang', 'Sedang — ditandai untuk tinjauan HR'), ('tinggi', 'Tinggi — ditolak')], default='rendah', max_length=10)),
                ('ditandai', models.BooleanField(default=False, verbose_name='Perlu tinjauan HR')),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('lokasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='presensi.lokasikantor')),
            ],
            options={
                'verbose_name': 'Presensi',
                'verbose_name_plural': 'Presensi',
            },
        ),
        migrations.CreateModel(
            name='LogKecurangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidn', models.CharField(db_index=True, max_length=20, verbose_name='NIDN Dosen')),
                ('jenis_anomali', models.CharField(max_length=100)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('skor', models.PositiveSmallIntegerField(default=0)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('presensi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presensi.presensi')),
            ],
            options={
                'verbose_name': 'Log Kecurangan',
                'verbose_name_plural': 'Log Kecurangan',
            },
        ),
        migrations.CreateModel(
            name='FotoPresensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('masuk', 'Masuk'), ('pulang', 'Pulang')], max_length=6)),
                ('berkas', models.FileField(blank=True, upload_to='presensi/selfie/%Y/%m/')),
                ('face_match_score', models.FloatField(blank=True, null=True)),
                ('liveness_score', models.FloatField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('presensi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='presensi.presensi')),
            ],
        ),
        migrations.CreateModel(
            name='QRToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=64, unique=True)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('kedaluwarsa', models.DateTimeField()),
                ('dipakai', models.BooleanField(default=False)),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_token', to='presensi.lokasikantor')),
            ],
        ),
        migrations.AddIndex(
            model_name='presensi',
            index=models.Index(fields=['tanggal', 'status'], name='presensi_pr_tanggal_99bd16_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='presensi',
            unique_together={('nidn', 'tanggal')},
        ),
    ]
