# Generated by Django 6.0.4 on 2026-07-29 05:30

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
import presensi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0004_finalisasi_kunci_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HariLibur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(unique=True)),
                ('keterangan', models.CharField(max_length=200)),
                ('jenis', models.CharField(choices=[('nasional', 'Libur Nasional'), ('cuti_bersama', 'Cuti Bersama'), ('kampus', 'Libur Kampus')], default='nasional', max_length=15)),
            ],
            options={
                'verbose_name': 'Hari Libur',
                'verbose_name_plural': 'Hari Libur',
                'ordering': ['tanggal'],
            },
        ),
        migrations.CreateModel(
            name='KelompokPresensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama kelompok')),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text='Kode role accounts.User yang otomatis masuk kelompok ini (mis. dosen, dekan).')),
                ('hari_kerja', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), default=presensi.models.default_hari_kerja, help_text='Hari kerja (0=Senin .. 6=Minggu).')),
                ('jam_masuk', models.TimeField(default=datetime.time(8, 0))),
                ('jam_pulang', models.TimeField(default=datetime.time(16, 0))),
                ('toleransi_menit', models.PositiveIntegerField(default=15, verbose_name='Toleransi telat (menit)')),
                ('aktif', models.BooleanField(default=True)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kelompok Presensi',
                'verbose_name_plural': 'Kelompok Presensi',
            },
        ),
        migrations.AddField(
            model_name='presensi',
            name='kelompok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presensi_set', to='presensi.kelompokpresensi'),
        ),
    ]
