# Generated by Django 6.0.4 on 2026-07-29 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0006_seed_kelompok_presensi'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetKerjaBulanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.PositiveSmallIntegerField(verbose_name='Bulan (1-12)')),
                ('tahun', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('target_hari_kerja', models.PositiveIntegerField(verbose_name='Target hari kerja')),
                ('target_jam_kerja', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Target jam kerja')),
                ('kelompok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_bulanan', to='presensi.kelompokpresensi')),
            ],
            options={
                'verbose_name': 'Target Kerja Bulanan',
                'verbose_name_plural': 'Target Kerja Bulanan',
                'ordering': ['-tahun', '-bulan', 'kelompok__nama'],
                'unique_together': {('kelompok', 'bulan', 'tahun')},
            },
        ),
    ]
