# Generated by Django 6.0.4 on 2026-07-29 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0008_seed_kelompok_staf_tendik'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='presensi',
            name='approver_lembur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lembur_disetujui_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presensi',
            name='keterangan_lembur',
            field=models.TextField(blank=True, help_text='Wajib diisi kalau lembur > 120 menit.', verbose_name='Keterangan lembur'),
        ),
        migrations.AddField(
            model_name='presensi',
            name='menit_lebih_awal',
            field=models.PositiveIntegerField(default=0, verbose_name='Datang lebih awal (menit)'),
        ),
        migrations.AddField(
            model_name='presensi',
            name='menit_lembur',
            field=models.PositiveIntegerField(default=0, verbose_name='Lembur (menit)'),
        ),
        migrations.AddField(
            model_name='presensi',
            name='menit_pulang_cepat',
            field=models.PositiveIntegerField(default=0, verbose_name='Pulang lebih cepat (menit)'),
        ),
        migrations.AddField(
            model_name='presensi',
            name='menit_terlambat',
            field=models.PositiveIntegerField(default=0, verbose_name='Terlambat (menit)'),
        ),
        migrations.AddField(
            model_name='presensi',
            name='status_lembur',
            field=models.CharField(choices=[('tidak_ada', 'Tidak Ada Lembur'), ('menunggu', 'Menunggu Persetujuan'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='tidak_ada', max_length=10),
        ),
        migrations.AddField(
            model_name='presensi',
            name='waktu_keputusan_lembur',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
