# Generated by Django 6.0.4 on 2026-07-30 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0009_tambah_field_lembur_presensi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParafDosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='presensi/paraf/%Y/%m/', verbose_name='Paraf')),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diperbarui', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paraf_presensi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paraf Dosen',
                'verbose_name_plural': 'Paraf Dosen',
            },
        ),
    ]
