# Generated by Django 6.0.4 on 2026-07-30 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0010_parafdosen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UrutanSerdos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.PositiveIntegerField(verbose_name='Nomor urut')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='urutan_serdos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Urutan Laporan Serdos',
                'verbose_name_plural': 'Urutan Laporan Serdos',
                'ordering': ['urutan'],
            },
        ),
    ]
