# Generated by Django 6.0.4 on 2026-08-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0011_urutanserdos'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelompokpresensi',
            name='otomatis_dari_jabatan_struktural',
            field=models.BooleanField(default=False, help_text='Kalau dicentang, kelompok ini SEKALIGUS berlaku otomatis untuk dosen/tendik yang tercatat AKTIF menjabat struktural di SIMDA (Kelola Jabatan Struktural) -- terlepas dari role akun login-nya. Dicek LEBIH DULU sebelum pencocokan `roles` biasa, lihat presensi.decision.resolve_kelompok.', verbose_name='Otomatis dari Jabatan Struktural (SIMDA)'),
        ),
    ]
