# Generated by Django 5.1.15 on 2026-07-12 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penelitian', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patenhki',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hki_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publikasikarya',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publikasi_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
