# Generated by Django 6.0.4 on 2026-07-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penelitian', '0002_alter_patenhki_user_alter_publikasikarya_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penelitian',
            name='in_kind',
        ),
    ]
