# Generated by Django 6.0.4 on 2026-07-25 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnggotaProfesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(blank=True, max_length=10, null=True)),
                ('kode_fakultas', models.CharField(blank=True, max_length=10, null=True)),
                ('kategori_kegiatan', models.CharField(choices=[('org_internasional_pengurus', 'Tingkat internasional sebagai pengurus'), ('org_internasional_anggota_permintaan', 'Tingkat internasional sebagai anggota atas permintaan'), ('org_internasional_anggota', 'Tingkat internasional sebagai anggota'), ('org_nasional_pengurus', 'Tingkat nasional sebagai pengurus'), ('org_nasional_anggota_permintaan', 'Tingkat nasional sebagai anggota atas permintaan'), ('org_nasional_anggota', 'Tingkat nasional sebagai anggota'), ('dosen_nasional_pengurus_aktif', 'Tingkat nasional sebagai pengurus aktif'), ('dosen_nasional_anggota_aktif', 'Tingkat nasional sebagai anggota aktif'), ('dosen_daerah_pengurus_aktif', 'Tingkat nasional provinsi/kabupaten/kota sebagai pengurus aktif'), ('dosen_daerah_anggota_aktif', 'Tingkat nasional provinsi/kabupaten/kota sebagai anggota aktif')], max_length=40)),
                ('nama_organisasi', models.CharField(max_length=200)),
                ('peran', models.CharField(max_length=150)),
                ('mulai_keanggotaan', models.DateField()),
                ('selesai_keanggotaan', models.DateField(blank=True, null=True)),
                ('instansi_profesi', models.CharField(blank=True, max_length=200)),
                ('semester', models.CharField(blank=True, choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap'), ('Keduanya', 'Keduanya')], max_length=10, null=True)),
                ('tahun_akademik', models.CharField(blank=True, max_length=10, null=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota_profesi_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anggota Profesi',
                'verbose_name_plural': 'Anggota Profesi',
                'ordering': ['-mulai_keanggotaan'],
            },
        ),
        migrations.CreateModel(
            name='Penghargaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(blank=True, max_length=10, null=True)),
                ('kode_fakultas', models.CharField(blank=True, max_length=10, null=True)),
                ('kategori_kegiatan', models.CharField(choices=[('satyalancana_30', 'Penghargaan/tanda jasa Satyalancana Karya Satya 30 tahun'), ('satyalancana_20', 'Penghargaan/tanda jasa Satyalancana Karya Satya 20 tahun'), ('satyalancana_10', 'Penghargaan/tanda jasa Satyalancana Karya Satya 10 tahun'), ('lainnya_internasional', 'Penghargaan lainnya tingkat internasional'), ('lainnya_nasional', 'Penghargaan lainnya tingkat nasional'), ('lainnya_provinsi_lokal', 'Penghargaan lainnya tingkat provinsi/lokal'), ('prestasi_internasional', 'Prestasi olahraga/humaniora tingkat internasional'), ('prestasi_nasional', 'Prestasi olahraga/humaniora tingkat nasional'), ('prestasi_daerah_lokal', 'Prestasi olahraga/humaniora tingkat daerah/lokal')], max_length=30)),
                ('tingkat_penghargaan', models.CharField(choices=[('sekolah', 'Sekolah'), ('kecamatan', 'Kecamatan'), ('kabkota', 'Kab/kota'), ('propinsi', 'Propinsi'), ('nasional', 'Nasional'), ('internasional', 'Internasional'), ('lainnya', 'Lainnya')], max_length=20)),
                ('jenis_penghargaan', models.CharField(blank=True, max_length=150)),
                ('nama_penghargaan', models.CharField(max_length=200)),
                ('tahun', models.IntegerField()),
                ('instansi_pemberi', models.CharField(max_length=200)),
                ('semester', models.CharField(blank=True, choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap'), ('Keduanya', 'Keduanya')], max_length=10, null=True)),
                ('tahun_akademik', models.CharField(blank=True, max_length=10, null=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penghargaan_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Penghargaan',
                'verbose_name_plural': 'Penghargaan',
                'ordering': ['-tahun'],
            },
        ),
        migrations.CreateModel(
            name='PenunjangLain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(blank=True, max_length=10, null=True)),
                ('kode_fakultas', models.CharField(blank=True, max_length=10, null=True)),
                ('kategori_kegiatan', models.CharField(blank=True, max_length=200)),
                ('nama_kegiatan', models.CharField(max_length=200)),
                ('jenis_kegiatan', models.CharField(choices=[('panitia_pt', 'Panitia/badan pada perguruan tinggi'), ('panitia_lembaga_pemerintah', 'Panitia/badan pada lembaga pemerintah'), ('delegasi_nasional', 'Delegasi nasional ke pertemuan internasional'), ('panitia_pertemuan_ilmiah', 'Panitia pada pertemuan ilmiah'), ('tim_penilai_jabatan_akademik', 'Tim penilai jabatan akademik dosen'), ('sebagai_anggota', 'Sebagai anggota'), ('panitia_lainnya', 'Panitia lainnya')], max_length=30)),
                ('instansi', models.CharField(max_length=200)),
                ('tingkat', models.CharField(choices=[('lokal', 'Lokal'), ('daerah', 'Daerah'), ('nasional', 'Nasional'), ('internasional', 'Internasional')], max_length=15)),
                ('no_sk_penugasan', models.CharField(blank=True, max_length=100)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField(blank=True, null=True)),
                ('semester', models.CharField(blank=True, choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap'), ('Keduanya', 'Keduanya')], max_length=10, null=True)),
                ('tahun_akademik', models.CharField(blank=True, max_length=10, null=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penunjang_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Penunjang Lain',
                'verbose_name_plural': 'Penunjang Lain',
                'ordering': ['-tanggal_mulai'],
            },
        ),
        migrations.CreateModel(
            name='AnggotaPenunjangLain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosen_id', models.IntegerField(help_text='id ke simda_dosen.DataDosen')),
                ('nama', models.CharField(max_length=150)),
                ('nidn', models.CharField(blank=True, max_length=20, verbose_name='NIDN')),
                ('perguruan_tinggi', models.CharField(blank=True, max_length=200)),
                ('peran', models.CharField(blank=True, max_length=150)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('penunjang_lain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota_set', to='penunjang.penunjanglain')),
            ],
            options={
                'verbose_name': 'Anggota Penunjang Lain',
                'verbose_name_plural': 'Anggota Penunjang Lain',
                'ordering': ['id'],
            },
        ),
    ]
