# Generated by Django 6.0.4 on 2026-04-09 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumenLain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_dokumen', models.CharField(max_length=50)),
                ('nama_dokumen', models.CharField(max_length=200)),
                ('no_dokumen', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_terbit', models.DateField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('link_dokumen', models.URLField(blank=True, null=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dokumen Lain',
                'verbose_name_plural': 'Dokumen Lain',
                'ordering': ['-tgl_input'],
            },
        ),
        migrations.CreateModel(
            name='ProfilDosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(blank=True, max_length=20, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10, null=True)),
                ('agama', models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katolik', 'Katolik'), ('Hindu', 'Hindu'), ('Buddha', 'Buddha'), ('Konghucu', 'Konghucu')], max_length=20, null=True)),
                ('status_pernikahan', models.CharField(blank=True, choices=[('Belum Menikah', 'Belum Menikah'), ('Menikah', 'Menikah'), ('Cerai', 'Cerai')], max_length=20, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('email_pribadi', models.EmailField(blank=True, max_length=254, null=True)),
                ('jabfung_aktif', models.CharField(blank=True, choices=[('Tenaga Pengajar', 'Tenaga Pengajar'), ('Asisten Ahli', 'Asisten Ahli'), ('Lektor', 'Lektor'), ('Lektor Kepala', 'Lektor Kepala'), ('Guru Besar', 'Guru Besar')], max_length=30, null=True)),
                ('pendidikan_terakhir', models.CharField(blank=True, choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=5, null=True)),
                ('bidang_keahlian', models.CharField(blank=True, max_length=100, null=True)),
                ('mata_kuliah_diampu', models.TextField(blank=True, null=True)),
                ('link_ktp', models.URLField(blank=True, null=True)),
                ('link_npwp', models.URLField(blank=True, null=True)),
                ('link_foto', models.URLField(blank=True, null=True)),
                ('link_sk_yayasan', models.URLField(blank=True, null=True)),
                ('tgl_update', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Dosen',
                'verbose_name_plural': 'Profil Dosen',
            },
        ),
        migrations.CreateModel(
            name='RiwayatJabfung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(choices=[('Tenaga Pengajar', 'Tenaga Pengajar'), ('Asisten Ahli', 'Asisten Ahli'), ('Lektor', 'Lektor'), ('Lektor Kepala', 'Lektor Kepala'), ('Guru Besar', 'Guru Besar')], max_length=30)),
                ('no_sk', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_sk', models.DateField(blank=True, null=True)),
                ('tmt_berlaku', models.DateField(blank=True, null=True)),
                ('instansi_penerbit', models.CharField(blank=True, max_length=100, null=True)),
                ('link_sk', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=10)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jabfung_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Riwayat Jabatan Fungsional',
                'verbose_name_plural': 'Riwayat Jabatan Fungsional',
                'ordering': ['-tgl_sk'],
            },
        ),
        migrations.CreateModel(
            name='RiwayatPendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenjang', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('D3', 'D3'), ('D4', 'D4')], max_length=5)),
                ('bidang_ilmu', models.CharField(max_length=100)),
                ('nama_pt', models.CharField(max_length=100)),
                ('kota_pt', models.CharField(blank=True, max_length=50, null=True)),
                ('negara', models.CharField(default='Indonesia', max_length=50)),
                ('tahun_masuk', models.IntegerField(blank=True, null=True)),
                ('tahun_lulus', models.IntegerField(blank=True, null=True)),
                ('no_ijazah', models.CharField(blank=True, max_length=50, null=True)),
                ('link_ijazah', models.URLField(blank=True, null=True)),
                ('link_transkrip', models.URLField(blank=True, null=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendidikan_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Riwayat Pendidikan',
                'verbose_name_plural': 'Riwayat Pendidikan',
                'ordering': ['-tahun_lulus'],
            },
        ),
        migrations.CreateModel(
            name='Sertifikat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_sertifikat', models.CharField(choices=[('Serdos', 'Sertifikat Dosen'), ('Kompetensi', 'Kompetensi'), ('Profesi', 'Profesi'), ('Internasional', 'Internasional'), ('Lainnya', 'Lainnya')], max_length=20)),
                ('nama_sertifikat', models.CharField(max_length=200)),
                ('no_sertifikat', models.CharField(blank=True, max_length=100, null=True)),
                ('lembaga_penerbit', models.CharField(blank=True, max_length=100, null=True)),
                ('tahun_terbit', models.IntegerField(blank=True, null=True)),
                ('masa_berlaku', models.CharField(blank=True, max_length=20, null=True)),
                ('link_sertifikat', models.URLField(blank=True, null=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sertifikat_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikat',
                'ordering': ['-tahun_terbit'],
            },
        ),
    ]
