# Generated by Django 6.0.4 on 2026-04-09 05:00

import django.db.models.deletion
import profil.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='profildosen',
            old_name='link_foto',
            new_name='link_dokumen_lain',
        ),
        migrations.RemoveField(
            model_name='profildosen',
            name='link_ktp',
        ),
        migrations.RemoveField(
            model_name='profildosen',
            name='link_npwp',
        ),
        migrations.RemoveField(
            model_name='profildosen',
            name='link_sk_yayasan',
        ),
        migrations.RemoveField(
            model_name='riwayatpendidikan',
            name='link_ijazah',
        ),
        migrations.RemoveField(
            model_name='riwayatpendidikan',
            name='link_transkrip',
        ),
        migrations.RemoveField(
            model_name='sertifikat',
            name='link_sertifikat',
        ),
        migrations.AddField(
            model_name='dokumenlain',
            name='file_dokumen',
            field=models.FileField(blank=True, null=True, upload_to=profil.models.upload_dokumen, validators=[profil.models.validate_file]),
        ),
        migrations.AddField(
            model_name='profildosen',
            name='file_ktp',
            field=models.FileField(blank=True, null=True, upload_to=profil.models.upload_ktp, validators=[profil.models.validate_file]),
        ),
        migrations.AddField(
            model_name='profildosen',
            name='file_npwp',
            field=models.FileField(blank=True, null=True, upload_to=profil.models.upload_npwp, validators=[profil.models.validate_file]),
        ),
        migrations.AddField(
            model_name='profildosen',
            name='file_sk_yayasan',
            field=models.FileField(blank=True, null=True, upload_to=profil.models.upload_sk_yayasan, validators=[profil.models.validate_file]),
        ),
        migrations.AddField(
            model_name='profildosen',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=profil.models.upload_profil, validators=[profil.models.validate_file]),
        ),
        migrations.AddField(
            model_name='riwayatjabfung',
            name='file_sk',
            field=models.FileField(blank=True, null=True, upload_to=profil.models.upload_jabfung, validators=[profil.models.validate_file]),
        ),
        migrations.AddField(
            model_name='riwayatpendidikan',
            name='file_ijazah',
            field=models.FileField(blank=True, null=True, upload_to=profil.models.upload_ijazah, validators=[profil.models.validate_file]),
        ),
        migrations.AddField(
            model_name='riwayatpendidikan',
            name='file_transkrip',
            field=models.FileField(blank=True, null=True, upload_to=profil.models.upload_transkrip, validators=[profil.models.validate_file]),
        ),
        migrations.AddField(
            model_name='sertifikat',
            name='file_sertifikat',
            field=models.FileField(blank=True, null=True, upload_to=profil.models.upload_sertifikat, validators=[profil.models.validate_file]),
        ),
        migrations.CreateModel(
            name='BKD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], max_length=10)),
                ('tahun_akademik', models.CharField(max_length=10)),
                ('file_bkd', models.FileField(blank=True, help_text='Upload file PDF BKD (max 5MB)', null=True, upload_to=profil.models.upload_bkd, validators=[profil.models.validate_file])),
                ('link_bkd', models.URLField(blank=True, help_text='Atau isi link Google Drive jika file besar', null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bkd_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BKD',
                'verbose_name_plural': 'BKD',
                'ordering': ['-tahun_akademik', 'semester'],
                'unique_together': {('user', 'semester', 'tahun_akademik')},
            },
        ),
    ]
