# Generated by Django 6.0.4 on 2026-04-09 13:05

import profil.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profildosen',
            old_name='link_foto',
            new_name='link_dokumen_lain',
        ),
        migrations.RemoveField(
            model_name='profildosen',
            name='link_ktp',
        ),
        migrations.RemoveField(
            model_name='profildosen',
            name='link_npwp',
        ),
        migrations.RemoveField(
            model_name='profildosen',
            name='link_sk_yayasan',
        ),
        migrations.RemoveField(
            model_name='riwayatpendidikan',
            name='link_ijazah',
        ),
        migrations.RemoveField(
            model_name='riwayatpendidikan',
            name='link_transkrip',
        ),
        migrations.RemoveField(
            model_name='sertifikat',
            name='link_sertifikat',
        ),
        migrations.AddField(
            model_name='dokumenlain',
            name='file_dokumen',
            field=models.FileField(blank=True, null=True, upload_to=profil.models.upload_dokumen, validators=[profil.models.validate_file]),
        ),
        migrations.AddField(
            model_name='profildosen',
            name='file_ktp',
            field=models.FileField(blank=True, null=True, upload_to=profil.models.upload_ktp, validators=[profil.models.validate_file]),
        ),
        migrations.AddField(
            model_name='profildosen',
            name='file_npwp',
            field=models.FileField(blank=True, null=True, upload_to=profil.models.upload_npwp, validators=[profil.models.validate_file]),
        ),
        migrations.AddField(
            model_name='profildosen',
            name='file_sk_yayasan',
            field=models.FileField(blank=True, null=True, upload_to=profil.models.upload_sk_yayasan, validators=[profil.models.validate_file]),
        ),
        migrations.AddField(
            model_name='profildosen',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=profil.models.upload_profil, validators=[profil.models.validate_file]),
        ),
        migrations.AddField(
            model_name='riwayatjabfung',
            name='file_sk',
            field=models.FileField(blank=True, null=True, upload_to=profil.models.upload_jabfung, validators=[profil.models.validate_file]),
        ),
        migrations.AddField(
            model_name='riwayatpendidikan',
            name='file_ijazah',
            field=models.FileField(blank=True, null=True, upload_to=profil.models.upload_ijazah, validators=[profil.models.validate_file]),
        ),
        migrations.AddField(
            model_name='riwayatpendidikan',
            name='file_transkrip',
            field=models.FileField(blank=True, null=True, upload_to=profil.models.upload_transkrip, validators=[profil.models.validate_file]),
        ),
        migrations.AddField(
            model_name='sertifikat',
            name='file_sertifikat',
            field=models.FileField(blank=True, null=True, upload_to=profil.models.upload_sertifikat, validators=[profil.models.validate_file]),
        ),
    ]
