# Generated by Django 6.0.4 on 2026-07-10 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_rename_link_foto_profildosen_link_dokumen_lain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riwayatjabfung',
            name='user',
        ),
        migrations.RemoveField(
            model_name='riwayatpendidikan',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProfilDosen',
        ),
        migrations.DeleteModel(
            name='RiwayatJabfung',
        ),
        migrations.DeleteModel(
            name='RiwayatPendidikan',
        ),
    ]
