# Generated by Django 6.0.4 on 2026-07-10 23:39

import django.db.models.deletion
import profil.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_remove_riwayatjabfung_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diklat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(blank=True, max_length=10, null=True)),
                ('kode_fakultas', models.CharField(blank=True, max_length=10, null=True)),
                ('jenis_diklat', models.CharField(choices=[('pelatihan_profesional', 'Pelatihan Profesional'), ('lemhanas', 'Lemhanas'), ('diklat_prajabatan', 'Diklat Prajabatan'), ('diklat_kepemimpinan', 'Diklat Kepemimpinan'), ('academic_exchange', 'Academic Exchange'), ('lainnya', 'Lainnya')], max_length=25)),
                ('nama_diklat', models.CharField(max_length=200)),
                ('penyelenggara', models.CharField(max_length=200)),
                ('peran', models.CharField(blank=True, max_length=100, null=True)),
                ('tingkatan', models.CharField(choices=[('Lokal', 'Lokal'), ('Regional', 'Regional'), ('Nasional', 'Nasional'), ('Internasional', 'Internasional')], max_length=15)),
                ('jumlah_jam', models.IntegerField(blank=True, null=True)),
                ('no_sertifikat', models.CharField(max_length=100)),
                ('tanggal_sertifikat', models.DateField()),
                ('tahun_penyelenggaraan', models.IntegerField()),
                ('tempat', models.CharField(blank=True, max_length=150, null=True)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('no_sk_penugasan', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_sk_penugasan', models.DateField(blank=True, null=True)),
                ('file_sertifikat', models.FileField(blank=True, null=True, upload_to=profil.models.upload_diklat, validators=[profil.models.validate_file])),
                ('semester', models.CharField(blank=True, choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap'), ('Keduanya', 'Keduanya')], max_length=10, null=True)),
                ('tahun_akademik', models.CharField(blank=True, max_length=10, null=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diklat_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diklat',
                'verbose_name_plural': 'Diklat',
                'ordering': ['-tahun_penyelenggaraan'],
            },
        ),
    ]
