# Generated by Django 6.0.4 on 2026-07-10 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_diklat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diklat',
            name='file_sertifikat',
        ),
    ]
