# Generated by Django 6.0.4 on 2026-07-11 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_remove_diklat_file_sertifikat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sertifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(blank=True, max_length=10, null=True)),
                ('kode_fakultas', models.CharField(blank=True, max_length=10, null=True)),
                ('jenis_sertifikasi', models.CharField(choices=[('serdos', 'Sertifikasi Dosen'), ('kompetensi', 'Sertifikasi Kompetensi'), ('profesi', 'Sertifikasi Profesi')], max_length=15)),
                ('bidang_studi', models.CharField(max_length=150)),
                ('lembaga_sertifikasi', models.CharField(blank=True, help_text='Diisi untuk Sertifikasi Kompetensi/Profesi', max_length=150, null=True)),
                ('no_registrasi_pendidik', models.CharField(blank=True, max_length=50, null=True)),
                ('no_peserta', models.CharField(blank=True, help_text='Diisi untuk Sertifikasi Dosen (Serdos)', max_length=50, null=True)),
                ('no_sk_sertifikasi', models.CharField(max_length=100)),
                ('tahun_sertifikasi', models.IntegerField()),
                ('tmt_sertifikasi', models.DateField(blank=True, help_text='Terhitung Mulai Tanggal -- diisi untuk Kompetensi/Profesi', null=True, verbose_name='TMT Sertifikasi')),
                ('tst_sertifikasi', models.DateField(blank=True, help_text='Tanggal Selesai Tugas -- diisi untuk Kompetensi/Profesi', null=True, verbose_name='TST Sertifikasi')),
                ('status_validasi', models.CharField(choices=[('menunggu', 'Menunggu Validasi'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='menunggu', max_length=15)),
                ('semester', models.CharField(blank=True, choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap'), ('Keduanya', 'Keduanya')], max_length=10, null=True)),
                ('tahun_akademik', models.CharField(blank=True, max_length=10, null=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sertifikasi_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sertifikasi',
                'verbose_name_plural': 'Sertifikasi',
                'ordering': ['-tahun_sertifikasi'],
            },
        ),
        migrations.CreateModel(
            name='TesKompetensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(blank=True, max_length=10, null=True)),
                ('kode_fakultas', models.CharField(blank=True, max_length=10, null=True)),
                ('jenis_tes', models.CharField(choices=[('ielts', 'IELTS'), ('toefl_ibt', 'TOEFL iBT'), ('toefl_itp', 'TOEFL ITP'), ('toeic', 'TOEIC'), ('tkbi', 'TKBI'), ('tkda', 'TKDA'), ('lainnya', 'Lainnya')], max_length=15)),
                ('nama_tes', models.CharField(max_length=150)),
                ('penyelenggara', models.CharField(max_length=150)),
                ('tanggal_tes', models.DateField()),
                ('tahun', models.IntegerField()),
                ('skor_tes', models.DecimalField(decimal_places=2, max_digits=7)),
                ('semester', models.CharField(blank=True, choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap'), ('Keduanya', 'Keduanya')], max_length=10, null=True)),
                ('tahun_akademik', models.CharField(blank=True, max_length=10, null=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tes_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tes Kompetensi',
                'verbose_name_plural': 'Tes Kompetensi',
                'ordering': ['-tahun'],
            },
        ),
        migrations.DeleteModel(
            name='Sertifikat',
        ),
    ]
