# Generated by Django 5.1.15 on 2026-07-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0006_sertifikasi_teskompetensi_delete_sertifikat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diklat',
            name='jenis_diklat',
            field=models.CharField(choices=[('aa', 'AA (Applied Approach)'), ('pekerti', 'Pekerti'), ('pelatihan_profesional', 'Pelatihan Profesional'), ('lemhanas', 'Lemhanas'), ('diklat_prajabatan', 'Diklat Prajabatan'), ('diklat_kepemimpinan', 'Diklat Kepemimpinan'), ('academic_exchange', 'Academic Exchange'), ('lainnya', 'Lainnya')], max_length=25),
        ),
    ]
