# Generated by Django 6.0.4 on 2026-07-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0007_alter_diklat_jenis_diklat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenlain',
            name='jenis_dokumen',
            field=models.CharField(choices=[('ktp', 'KTP'), ('kartu_keluarga', 'Kartu Keluarga'), ('npwp', 'NPWP'), ('sk_pangkat_inpassing', 'SK Pangkat/Inpassing'), ('sk_jabatan_fungsional', 'SK Jabatan Fungsional'), ('lainnya', 'Lainnya')], max_length=50),
        ),
    ]
