# Generated by Django 6.0.4 on 2026-07-25 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JabatanStruktural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(blank=True, max_length=10, null=True)),
                ('kode_fakultas', models.CharField(blank=True, max_length=10, null=True)),
                ('jabatan_tugas', models.CharField(max_length=150)),
                ('no_sk_jabatan_struktural', models.CharField(blank=True, max_length=100, verbose_name='Nomor SK Jabatan Struktural')),
                ('terhitung_mulai_tanggal', models.DateField()),
                ('terhitung_selesai_tanggal', models.DateField(blank=True, null=True)),
                ('lokasi_penugasan', models.CharField(max_length=200)),
                ('semester', models.CharField(blank=True, choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap'), ('Keduanya', 'Keduanya')], max_length=10, null=True)),
                ('tahun_akademik', models.CharField(blank=True, max_length=10, null=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jabatan_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jabatan Struktural',
                'verbose_name_plural': 'Jabatan Struktural',
                'ordering': ['-terhitung_mulai_tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Pembicara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(blank=True, max_length=10, null=True)),
                ('kode_fakultas', models.CharField(blank=True, max_length=10, null=True)),
                ('kategori_kegiatan', models.CharField(choices=[('terjadwal_semester_internasional', 'Terjadwal/terprogram dalam satu semester atau lebih (tingkat internasional)'), ('terjadwal_semester_nasional', 'Terjadwal/terprogram dalam satu semester atau lebih (tingkat nasional)'), ('terjadwal_semester_lokal', 'Terjadwal/terprogram dalam satu semester atau lebih (tingkat lokal)'), ('terjadwal_bulan_internasional', 'Terjadwal/terprogram kurang dari satu semester dan minimal satu bulan (tingkat internasional)'), ('terjadwal_bulan_nasional', 'Terjadwal/terprogram kurang dari satu semester dan minimal satu bulan (tingkat nasional)'), ('terjadwal_bulan_lokal', 'Terjadwal/terprogram kurang dari satu semester dan minimal satu bulan (tingkat lokal)'), ('insidential_internasional', 'Insidential (tingkat internasional)'), ('insidential_nasional', 'Insidential (tingkat nasional)'), ('insidential_lokal', 'Insidential (tingkat lokal)')], max_length=40)),
                ('kategori_capaian_luaran', models.CharField(blank=True, max_length=150)),
                ('litabmas', models.CharField(blank=True, max_length=200)),
                ('kategori_pembicara', models.CharField(blank=True, max_length=100)),
                ('judul_makalah', models.TextField()),
                ('nama_pertemuan_ilmiah', models.CharField(max_length=200)),
                ('tingkat_pertemuan', models.CharField(blank=True, max_length=100)),
                ('penyelenggara', models.CharField(max_length=200)),
                ('tanggal_pelaksanaan', models.DateField()),
                ('bahasa', models.CharField(blank=True, max_length=50)),
                ('no_sk_penugasan', models.CharField(blank=True, max_length=100)),
                ('tanggal_sk_penugasan', models.DateField(blank=True, null=True)),
                ('semester', models.CharField(blank=True, choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap'), ('Keduanya', 'Keduanya')], max_length=10, null=True)),
                ('tahun_akademik', models.CharField(blank=True, max_length=10, null=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembicara_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pembicara',
                'verbose_name_plural': 'Pembicara',
                'ordering': ['-tanggal_pelaksanaan'],
            },
        ),
        migrations.CreateModel(
            name='Pengabdian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(blank=True, max_length=10, null=True)),
                ('kode_fakultas', models.CharField(blank=True, max_length=10, null=True)),
                ('kategori_kegiatan', models.CharField(choices=[('pengembangan_hasil', 'Melaksanakan pengembangan hasil pendidikan dan penelitian'), ('pelayanan_masyarakat', 'Memberi pelayanan kepada masyarakat atau kegiatan lain yang menunjang pelaksanaan tugas umum pemerintah dan pembangunan')], max_length=25)),
                ('judul_kegiatan', models.TextField()),
                ('afiliasi', models.CharField(blank=True, max_length=200)),
                ('kelompok_bidang', models.CharField(blank=True, max_length=150)),
                ('litabmas_sebelumnya', models.CharField(blank=True, max_length=200, verbose_name='Litabmas Sebelumnya')),
                ('jenis_skim', models.CharField(blank=True, max_length=150, verbose_name='Jenis SKIM')),
                ('lokasi_kegiatan', models.CharField(blank=True, max_length=200)),
                ('tahun_usulan', models.IntegerField()),
                ('tahun_kegiatan', models.CharField(help_text='Contoh: 2025/2026', max_length=10)),
                ('tahun_pelaksanaan', models.IntegerField()),
                ('lama_kegiatan_tahun', models.IntegerField(default=1, verbose_name='Lama Kegiatan (Tahun)')),
                ('tahun_pelaksanaan_ke', models.IntegerField(default=1)),
                ('dana_dikti', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Dana dari Dikti (Rp)')),
                ('dana_pt', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Dana dari Perguruan Tinggi (Rp)')),
                ('dana_institusi_lain', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Dana dari Institusi Lain (Rp)')),
                ('in_kind', models.CharField(blank=True, max_length=200, verbose_name='In Kind')),
                ('no_sk_penugasan', models.CharField(blank=True, max_length=100)),
                ('tanggal_sk_penugasan', models.DateField(blank=True, null=True)),
                ('mitra_litabmas', models.CharField(blank=True, max_length=200)),
                ('semester', models.CharField(blank=True, choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap'), ('Keduanya', 'Keduanya')], max_length=10, null=True)),
                ('tahun_akademik', models.CharField(blank=True, max_length=10, null=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pkm_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengabdian',
                'verbose_name_plural': 'Pengabdian',
                'ordering': ['-tahun_pelaksanaan'],
            },
        ),
        migrations.CreateModel(
            name='AnggotaPengabdian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_anggota', models.CharField(choices=[('dosen', 'Dosen'), ('mahasiswa', 'Mahasiswa'), ('kolaborator_eksternal', 'Kolaborator Eksternal')], max_length=25)),
                ('dosen_id', models.IntegerField(blank=True, help_text='id ke simda_dosen.DataDosen', null=True)),
                ('mahasiswa_id', models.IntegerField(blank=True, help_text='id ke simda_dosen.MahasiswaPublik', null=True)),
                ('nama', models.CharField(max_length=150)),
                ('nidn_nim', models.CharField(blank=True, max_length=20, verbose_name='NIDN/NIM')),
                ('perguruan_tinggi', models.CharField(blank=True, max_length=200)),
                ('peran', models.CharField(choices=[('ketua', 'Ketua'), ('anggota', 'Anggota')], default='anggota', max_length=10)),
                ('status_aktif', models.BooleanField(default=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('pengabdian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota_set', to='pengabdian.pengabdian')),
            ],
            options={
                'verbose_name': 'Anggota Pengabdian',
                'verbose_name_plural': 'Anggota Pengabdian',
                'ordering': ['jenis_anggota', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PengelolaJurnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(blank=True, max_length=10, null=True)),
                ('kode_fakultas', models.CharField(blank=True, max_length=10, null=True)),
                ('nama_jurnal', models.CharField(max_length=200)),
                ('media_publikasi', models.CharField(blank=True, max_length=150)),
                ('peran', models.CharField(max_length=100)),
                ('no_sk_penugasan', models.CharField(blank=True, max_length=100)),
                ('terhitung_mulai_tanggal', models.DateField()),
                ('tanggal_selesai', models.DateField(blank=True, null=True)),
                ('status_aktif', models.BooleanField(default=True)),
                ('semester', models.CharField(blank=True, choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap'), ('Keduanya', 'Keduanya')], max_length=10, null=True)),
                ('tahun_akademik', models.CharField(blank=True, max_length=10, null=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurnal_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengelola Jurnal',
                'verbose_name_plural': 'Pengelola Jurnal',
                'ordering': ['-terhitung_mulai_tanggal'],
            },
        ),
    ]
