# Generated by Django 6.0.4 on 2026-07-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengabdian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembicara',
            name='tingkat_pertemuan',
            field=models.CharField(blank=True, choices=[('lokal', 'Lokal'), ('daerah', 'Daerah'), ('nasional', 'Nasional'), ('internasional', 'Internasional'), ('lain_lain', 'Lain-lain')], max_length=20),
        ),
    ]
