# Generated by Django 6.0.4 on 2026-07-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengabdian', '0002_alter_pembicara_tingkat_pertemuan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembicara',
            name='kategori_pembicara',
            field=models.CharField(blank=True, choices=[('pertemuan_ilmiah', 'Pembicara pada pertemuan ilmiah'), ('pembicara_kunci', 'Pembicara kunci'), ('pelatihan_penyuluhan_ceramah', 'Pembicara/narasumber pada pelatihan/penyuluhan/ceramah')], max_length=30),
        ),
    ]
