# Generated by Django 6.0.4 on 2026-07-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengabdian', '0003_alter_pembicara_kategori_pembicara'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengabdian',
            name='in_kind',
        ),
    ]
