# Generated by Django 6.0.4 on 2026-07-25 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(blank=True, max_length=10, null=True)),
                ('kode_fakultas', models.CharField(blank=True, max_length=10, null=True)),
                ('jenis_beasiswa', models.CharField(choices=[('prestasi', 'Prestasi'), ('kemiskinan', 'Kemiskinan'), ('pendidikan', 'Pendidikan'), ('unggulan', 'Unggulan'), ('ikatan_dinas', 'Ikatan Dinas'), ('peningkatan_karir', 'Peningkatan Karir'), ('lainnya', 'Lainnya')], max_length=20)),
                ('nama_beasiswa', models.CharField(max_length=200)),
                ('tahun_mulai', models.IntegerField()),
                ('tahun_selesai', models.IntegerField(blank=True, null=True)),
                ('masih_terima', models.BooleanField(default=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beasiswa_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beasiswa',
                'verbose_name_plural': 'Beasiswa',
                'ordering': ['-tahun_mulai'],
            },
        ),
        migrations.CreateModel(
            name='Kesejahteraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(blank=True, max_length=10, null=True)),
                ('kode_fakultas', models.CharField(blank=True, max_length=10, null=True)),
                ('jenis_kesejahteraan', models.CharField(choices=[('asuransi_kesejahteraan', 'Asuransi Kesejahteraan'), ('dana_pensiun', 'Dana Pensiun'), ('jamkesmas', 'Jamkesmas'), ('jamsostek', 'Jamsostek'), ('lainnya', 'Lainnya')], max_length=30)),
                ('layanan_kesejahteraan', models.CharField(max_length=200)),
                ('penyelenggara', models.CharField(max_length=200)),
                ('tahun_mulai', models.IntegerField()),
                ('tahun_selesai', models.IntegerField(blank=True, null=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kesejahteraan_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kesejahteraan',
                'verbose_name_plural': 'Kesejahteraan',
                'ordering': ['-tahun_mulai'],
            },
        ),
        migrations.CreateModel(
            name='Tunjangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(blank=True, max_length=10, null=True)),
                ('kode_fakultas', models.CharField(blank=True, max_length=10, null=True)),
                ('jenis_tunjangan', models.CharField(choices=[('tunjangan_anak', 'Tunjangan Anak'), ('tunjangan_istri_suami', 'Tunjangan Istri/Suami'), ('tunjangan_beras', 'Tunjangan Beras'), ('tunjangan_umum_pns', 'Tunjangan Umum PNS'), ('tunjangan_khusus_guru_dosen', 'Tunjangan Khusus Guru/Dosen'), ('tunjangan_medis', 'Tunjangan Medis'), ('tunjangan_pegawai_non_pns', 'Tunjangan Pegawai Non PNS'), ('tunjangan_hari_tua', 'Tunjangan Hari Tua'), ('bantuan_kualifikasi_akademik', 'Bantuan Peningkatan Kualifikasi Akademik'), ('tunjangan_guru_daerah_khusus', 'Tunjangan Guru Daerah Khusus'), ('tunjangan_fungsional_non_pns', 'Tunjangan Fungsional Non PNS'), ('tunjangan_pendidikan_layanan_khusus', 'Tunjangan Pendidikan Khusus & Layanan Khusus'), ('lainnya', 'Lainnya')], max_length=40)),
                ('nama_tunjangan', models.CharField(max_length=200)),
                ('instansi_pemberi_tunjangan', models.CharField(blank=True, max_length=200)),
                ('sumber_dana', models.CharField(blank=True, max_length=150)),
                ('tahun_mulai', models.IntegerField()),
                ('tahun_selesai', models.IntegerField(blank=True, null=True)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tunjangan_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tunjangan',
                'verbose_name_plural': 'Tunjangan',
                'ordering': ['-tahun_mulai'],
            },
        ),
    ]
