# Generated by Django 5.1.15 on 2026-07-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simda_dosen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MahasiswaPublik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20)),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('kode_prodi', models.CharField(db_column='kode_prodi', max_length=10)),
                ('angkatan', models.CharField(max_length=10)),
                ('semester_aktif', models.IntegerField()),
                ('status_mahasiswa', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Mahasiswa (SIMDA)',
                'verbose_name_plural': 'Mahasiswa (SIMDA)',
                'db_table': 'master"."v_mahasiswa_publik',
                'ordering': ['kode_prodi', 'nama_lengkap'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MataKuliahPublik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_mk', models.CharField(max_length=20)),
                ('kode_mk_dikti', models.CharField(blank=True, max_length=20)),
                ('nama_mk', models.CharField(max_length=200)),
                ('kode_prodi', models.CharField(db_column='kode_prodi', max_length=10)),
                ('sks_total', models.IntegerField()),
                ('jenis_mk', models.CharField(choices=[('Wajib', 'Wajib'), ('Pilihan', 'Pilihan'), ('KKN', 'KKN'), ('Skripsi', 'Skripsi'), ('Tesis', 'Tesis'), ('Magang', 'Magang')], max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mata Kuliah (SIMDA)',
                'verbose_name_plural': 'Mata Kuliah (SIMDA)',
                'db_table': 'master"."mata_kuliah',
                'ordering': ['kode_prodi', 'kode_mk'],
                'managed': False,
            },
        ),
    ]
