# Generated by Django 6.0.4 on 2026-07-25 14:17

import simda_dosen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simda_dosen', '0002_mahasiswapublik_matakuliahpublik'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidangKeahlianPublik',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kode', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=150)),
                ('rumpun_ilmu', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Bidang Keahlian (SIMDA)',
                'verbose_name_plural': 'Bidang Keahlian (SIMDA)',
                'db_table': 'master"."v_bidang_keahlian_publik',
                'ordering': ['nama'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GolonganPublik',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kode', models.CharField(max_length=5)),
                ('nama', models.CharField(max_length=50)),
                ('pangkat', models.CharField(blank=True, max_length=100)),
                ('urutan', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Golongan (SIMDA)',
                'verbose_name_plural': 'Golongan (SIMDA)',
                'db_table': 'master"."v_golongan_publik',
                'ordering': ['urutan'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiwayatPangkatGolongan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golongan_id', models.IntegerField()),
                ('no_sk', models.CharField(max_length=100, verbose_name='Nomor SK Inpassing')),
                ('tgl_sk', models.DateField(blank=True, null=True, verbose_name='Tanggal SK')),
                ('tmt', models.DateField(verbose_name='TMT')),
                ('angka_kredit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('masa_kerja_tahun', models.IntegerField(default=0, verbose_name='Masa Kerja (Tahun)')),
                ('masa_kerja_bulan', models.IntegerField(default=0, verbose_name='Masa Kerja (Bulan)')),
                ('file_sk', models.FileField(blank=True, null=True, upload_to='dosen/pangkat_sk/', validators=[simda_dosen.models.validate_file_size])),
                ('url_sk', models.URLField(blank=True, verbose_name='Link SK (alternatif)')),
            ],
            options={
                'verbose_name': 'Riwayat Pangkat/Golongan (SIMDA)',
                'verbose_name_plural': 'Riwayat Pangkat/Golongan (SIMDA)',
                'db_table': 'master"."riwayat_pangkat_golongan',
                'ordering': ['-tmt'],
                'managed': False,
            },
        ),
    ]
