# Generated by Django 6.0.4 on 2026-07-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simda_dosen', '0003_bidangkeahlianpublik_golonganpublik_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisKepegawaianPublik',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kode', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=100)),
                ('urutan', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Jenis Kepegawaian (SIMDA)',
                'verbose_name_plural': 'Jenis Kepegawaian (SIMDA)',
                'db_table': 'master"."v_jenis_kepegawaian_publik',
                'ordering': ['urutan'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusKepegawaianPublik',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kode', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=50)),
                ('urutan', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Status Keaktifan (SIMDA)',
                'verbose_name_plural': 'Status Keaktifan (SIMDA)',
                'db_table': 'master"."v_status_kepegawaian_publik',
                'ordering': ['urutan'],
                'managed': False,
            },
        ),
    ]
