# Generated by Django 6.0.4 on 2026-07-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simda_dosen', '0004_jeniskepegawaianpublik_statuskepegawaianpublik'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidangKeahlian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=150)),
                ('rumpun_ilmu', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bidang Keahlian (tulis)',
                'verbose_name_plural': 'Bidang Keahlian (tulis)',
                'db_table': 'master"."bidang_keahlian',
                'ordering': ['nama'],
                'managed': False,
            },
        ),
    ]
