# Generated by Django 6.0.4 on 2026-07-30 04:35

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simda_dosen', '0005_bidangkeahlian'),
    ]

    operations = [
        migrations.CreateModel(
            name='JabatanStruktural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('singkatan', models.CharField(blank=True, max_length=20)),
                ('level', models.IntegerField(help_text='1=Rektorat, 2=Dekan, 3=Kaprodi, 4=Kepala Unit')),
                ('lingkup', models.CharField(choices=[('universitas', 'Universitas'), ('fakultas', 'Fakultas'), ('prodi', 'Program Studi'), ('unit', 'Unit Kerja')], max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Jabatan Struktural (SIMDA)',
                'verbose_name_plural': 'Jabatan Struktural (SIMDA)',
                'db_table': 'master"."jabatan_struktural',
                'ordering': ['level'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PejabatStruktural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tendik_id', models.IntegerField(blank=True, null=True)),
                ('kode_fakultas', models.CharField(blank=True, max_length=10)),
                ('kode_prodi', models.CharField(blank=True, max_length=10)),
                ('tgl_mulai', models.DateField()),
                ('tgl_selesai', models.DateField(blank=True, null=True)),
                ('is_aktif', models.BooleanField(default=True)),
                ('file_ttd', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='https://master.unisan-g.id/media/', location='C:\\unisan\\simda\\media'), upload_to='pejabat/ttd/', verbose_name='File Tanda Tangan')),
                ('lebar_ttd', models.IntegerField(default=60, verbose_name='Lebar TTD (mm)')),
                ('tinggi_ttd', models.IntegerField(default=25, verbose_name='Tinggi TTD (mm)')),
            ],
            options={
                'verbose_name': 'Pejabat Struktural (SIMDA)',
                'verbose_name_plural': 'Pejabat Struktural (SIMDA)',
                'db_table': 'master"."pejabat_struktural',
                'ordering': ['jabatan__level', '-tgl_mulai'],
                'managed': False,
            },
        ),
    ]
