# Generated by Django 6.0.4 on 2026-08-01 14:23
#
# RemoveField/AddField untuk PejabatStruktural.tendik ditambahkan MANUAL
# (bukan hasil `makemigrations`) -- autodetector Django tidak melacak
# perubahan field pada model managed=False yang SUDAH ada sebelumnya
# (lihat penjelasan lengkap di migrasi 0007 versi sebelumnya / commit
# 9e59748). Ini cuma soal state bookkeeping migrasi, TIDAK ada SQL nyata
# yang dieksekusi untuk model unmanaged.

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simda_dosen', '0006_jabatanstruktural_pejabatstruktural'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTendik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sso_user_id', models.IntegerField(blank=True, null=True)),
                ('nip', models.CharField(blank=True, max_length=30)),
                ('nip_yayasan', models.CharField(blank=True, db_index=True, max_length=30)),
                ('nik', models.CharField(blank=True, max_length=20)),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('tempat_lahir', models.CharField(blank=True, max_length=100)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('pendidikan_terakhir', models.CharField(blank=True, choices=[('SMA', 'SMA/Sederajat'), ('D3', 'D3'), ('S1', 'S1'), ('S2', 'S2')], max_length=5)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('unit_kerja_id', models.IntegerField(blank=True, null=True)),
                ('jabatan', models.CharField(blank=True, help_text='Jabatan/jobdesk sehari-hari, BUKAN jabatan struktural (lihat JabatanStruktural/PejabatStruktural)', max_length=100)),
                ('jenis_kepegawaian_id', models.IntegerField(blank=True, null=True)),
                ('status_kepegawaian_id', models.IntegerField(blank=True, null=True)),
                ('golongan_id', models.IntegerField(blank=True, null=True)),
                ('tgl_mulai_kerja', models.DateField(blank=True, null=True)),
                ('nama_bank', models.CharField(blank=True, max_length=50)),
                ('no_rekening', models.CharField(blank=True, max_length=30)),
                ('atas_nama_rekening', models.CharField(blank=True, max_length=150)),
                ('foto', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='https://master.unisan-g.id/media/', location='C:\\unisan\\simda\\media'), upload_to='tendik/foto/')),
                ('is_active', models.BooleanField(default=True)),
                ('tgl_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tgl_diperbarui', models.DateTimeField(auto_now=True)),
                ('agama_id', models.IntegerField(blank=True, null=True)),
                ('status_pernikahan', models.CharField(blank=True, max_length=20)),
                ('alamat_domisili', models.TextField(blank=True)),
                ('provinsi_domisili_id', models.IntegerField(blank=True, null=True)),
                ('kabupaten_domisili_id', models.IntegerField(blank=True, null=True)),
                ('kode_pos', models.CharField(blank=True, max_length=5)),
                ('bidang_keahlian', models.CharField(blank=True, max_length=150)),
                ('no_sk_pengangkatan', models.CharField(blank=True, max_length=100)),
                ('tgl_sk_pengangkatan', models.DateField(blank=True, null=True)),
                ('npwp', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Data Tendik (SIMDA)',
                'verbose_name_plural': 'Data Tendik (SIMDA)',
                'db_table': 'master"."data_tendik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=150)),
                ('singkatan', models.CharField(blank=True, max_length=30)),
                ('jenis', models.CharField(choices=[('akademik', 'Akademik'), ('administrasi', 'Administrasi'), ('penunjang', 'Penunjang'), ('layanan', 'Layanan'), ('penelitian', 'Penelitian')], max_length=20)),
                ('induk_id', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('no_telepon', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unit Kerja (SIMDA)',
                'verbose_name_plural': 'Unit Kerja (SIMDA)',
                'db_table': 'master"."unit_kerja',
                'ordering': ['jenis', 'nama'],
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='pejabatstruktural',
            name='tendik_id',
        ),
        migrations.AddField(
            model_name='pejabatstruktural',
            name='tendik',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='jabatan_struktural', to='simda_dosen.datatendik',
            ),
        ),
    ]
