# Generated by Django 6.0.4 on 2026-08-01 06:43
#
# RemoveField/AddField untuk PejabatStruktural.tendik ditambahkan MANUAL
# (bukan hasil `makemigrations`) -- autodetector Django tidak melacak
# perubahan field pada model managed=False yang SUDAH ada sebelumnya
# (lihat MigrationAutodetector._prepare_field_lists(), field_keys cuma
# dibangun dari kept_model_keys = old_model_keys & new_model_keys, dan
# unmanaged models sengaja dipisah ke *_unmanaged_keys, tidak pernah
# masuk *_model_keys). Ini cuma soal state bookkeeping migrasi, TIDAK
# ada SQL nyata yang dieksekusi untuk model unmanaged, jadi aman.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simda_dosen', '0006_jabatanstruktural_pejabatstruktural'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTendik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(blank=True, max_length=30)),
                ('nip_yayasan', models.CharField(blank=True, db_index=True, max_length=30)),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('unit_kerja_id', models.IntegerField(blank=True, null=True)),
                ('jabatan', models.CharField(blank=True, help_text='Jabatan/jobdesk sehari-hari, BUKAN jabatan struktural (lihat JabatanStruktural/PejabatStruktural)', max_length=100)),
                ('jenis_kepegawaian_id', models.IntegerField(blank=True, null=True)),
                ('status_kepegawaian_id', models.IntegerField(blank=True, null=True)),
                ('golongan_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Data Tendik (SIMDA)',
                'verbose_name_plural': 'Data Tendik (SIMDA)',
                'db_table': 'master"."v_tendik_ringkas',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='pejabatstruktural',
            name='tendik_id',
        ),
        migrations.AddField(
            model_name='pejabatstruktural',
            name='tendik',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='jabatan_struktural', to='simda_dosen.datatendik',
            ),
        ),
    ]
