# Generated by Django 6.0.4 on 2026-08-04 05:32

import django.core.files.storage
import simda_dosen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simda_dosen', '0007_datatendik_unitkerja'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatPelatihanTendik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelatihan', models.CharField(max_length=200)),
                ('penyelenggara', models.CharField(max_length=200)),
                ('tingkat', models.CharField(choices=[('Lokal', 'Lokal'), ('Regional', 'Regional'), ('Nasional', 'Nasional'), ('Internasional', 'Internasional')], max_length=15)),
                ('jumlah_jam', models.IntegerField(blank=True, null=True)),
                ('no_sertifikat', models.CharField(blank=True, max_length=100)),
                ('tanggal_mulai', models.DateField(blank=True, null=True)),
                ('tanggal_selesai', models.DateField(blank=True, null=True)),
                ('file_sertifikat', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='https://master.unisan-g.id/media/', location='C:\\unisan\\simda\\media'), upload_to='tendik/pelatihan/', validators=[simda_dosen.models.validate_file_size])),
                ('keterangan', models.TextField(blank=True)),
                ('tgl_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tgl_diperbarui', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Riwayat Pelatihan Tendik (SIMDA)',
                'verbose_name_plural': 'Riwayat Pelatihan Tendik (SIMDA)',
                'db_table': 'master"."riwayat_pelatihan_tendik',
                'ordering': ['-tanggal_mulai'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiwayatPendidikanTendik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenjang', models.CharField(choices=[('SMA', 'SMA/Sederajat'), ('D3', 'D3'), ('S1', 'S1'), ('S2', 'S2')], max_length=5)),
                ('institusi', models.CharField(max_length=200)),
                ('jurusan', models.CharField(blank=True, max_length=150)),
                ('tahun_masuk', models.IntegerField(blank=True, null=True)),
                ('tahun_lulus', models.IntegerField(blank=True, null=True)),
                ('no_ijazah', models.CharField(blank=True, max_length=50)),
                ('file_ijazah', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='https://master.unisan-g.id/media/', location='C:\\unisan\\simda\\media'), upload_to='tendik/ijazah/', validators=[simda_dosen.models.validate_file_size])),
                ('keterangan', models.TextField(blank=True)),
                ('tgl_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tgl_diperbarui', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Riwayat Pendidikan Tendik (SIMDA)',
                'verbose_name_plural': 'Riwayat Pendidikan Tendik (SIMDA)',
                'db_table': 'master"."riwayat_pendidikan_tendik',
                'ordering': ['-tahun_lulus'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiwayatPrestasiTendik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_prestasi', models.CharField(max_length=200)),
                ('pemberi_penghargaan', models.CharField(blank=True, max_length=200)),
                ('tingkat', models.CharField(choices=[('Lokal', 'Lokal'), ('Regional', 'Regional'), ('Nasional', 'Nasional'), ('Internasional', 'Internasional')], max_length=15)),
                ('tahun', models.IntegerField(blank=True, null=True)),
                ('no_sertifikat', models.CharField(blank=True, max_length=100)),
                ('file_bukti', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='https://master.unisan-g.id/media/', location='C:\\unisan\\simda\\media'), upload_to='tendik/prestasi/', validators=[simda_dosen.models.validate_file_size])),
                ('keterangan', models.TextField(blank=True)),
                ('tgl_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tgl_diperbarui', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Riwayat Prestasi Tendik (SIMDA)',
                'verbose_name_plural': 'Riwayat Prestasi Tendik (SIMDA)',
                'db_table': 'master"."riwayat_prestasi_tendik',
                'ordering': ['-tahun'],
                'managed': False,
            },
        ),
    ]
