# Generated by Django 5.1.15 on 2026-07-12 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendidikan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenulisBahanAjar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_penulis', models.CharField(choices=[('dosen', 'Dosen'), ('mahasiswa', 'Mahasiswa'), ('lain', 'Lainnya')], max_length=10)),
                ('dosen_id', models.IntegerField(blank=True, help_text='id ke simda_dosen.DataDosen, diisi kalau jenis_penulis=dosen', null=True)),
                ('mahasiswa_id', models.IntegerField(blank=True, help_text='id ke simda_dosen.MahasiswaPublik, diisi kalau jenis_penulis=mahasiswa', null=True)),
                ('nama', models.CharField(max_length=150)),
                ('nidn_nim', models.CharField(blank=True, max_length=20, verbose_name='NIDN/NIM')),
                ('urutan', models.IntegerField(default=1)),
                ('afiliasi', models.CharField(blank=True, max_length=200)),
                ('peran', models.CharField(choices=[('penulis', 'Penulis'), ('editor', 'Editor'), ('penerjemah', 'Penerjemah'), ('penemu_inventor', 'Penemu/Inventor')], default='penulis', max_length=20)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('bahan_ajar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penulis_set', to='pendidikan.bahanajar')),
            ],
            options={
                'verbose_name': 'Penulis Bahan Ajar',
                'verbose_name_plural': 'Penulis Bahan Ajar',
                'ordering': ['urutan'],
            },
        ),
    ]
