# Generated by Django 5.1.15 on 2026-07-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendidikan', '0002_penulisbahanajar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembinaanmahasiswa',
            name='jenis_kegiatan',
            field=models.CharField(choices=[('penasehat_akademik', 'Penasehat Akademik'), ('pembina_ukm', 'Pembina UKM'), ('pembina_ormawa', 'Pembina Ormawa'), ('pembina_kompetisi', 'Pembina Kompetisi Mahasiswa'), ('lainnya', 'Lainnya')], max_length=20),
        ),
    ]
