# Generated by Django 6.0.4 on 2026-04-09 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HKI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(max_length=10)),
                ('kode_fakultas', models.CharField(max_length=10)),
                ('judul', models.TextField()),
                ('jenis_hki', models.CharField(choices=[('Paten', 'Paten'), ('Paten Sederhana', 'Paten Sederhana'), ('Hak Cipta', 'Hak Cipta'), ('Merek', 'Merek'), ('Desain Industri', 'Desain Industri'), ('Lainnya', 'Lainnya')], max_length=30)),
                ('no_hki', models.CharField(blank=True, max_length=100, null=True)),
                ('tahun_perolehan', models.IntegerField(blank=True, null=True)),
                ('tahun_akademik', models.CharField(max_length=10)),
                ('link_bukti', models.URLField(blank=True, null=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hki_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HKI',
                'verbose_name_plural': 'HKI',
                'ordering': ['-tahun_akademik'],
            },
        ),
        migrations.CreateModel(
            name='Penelitian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(max_length=10)),
                ('kode_fakultas', models.CharField(max_length=10)),
                ('judul', models.TextField()),
                ('jml_mahasiswa', models.IntegerField(default=0)),
                ('jenis_hibah', models.CharField(blank=True, max_length=100, null=True)),
                ('sumber', models.CharField(blank=True, max_length=100, null=True)),
                ('durasi', models.IntegerField(default=1)),
                ('ln_i', models.CharField(blank=True, choices=[('L', 'Lokal'), ('N', 'Nasional'), ('I', 'Internasional')], max_length=5, null=True)),
                ('tahun_akademik', models.CharField(max_length=10)),
                ('pendanaan', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('link_bukti', models.URLField(blank=True, null=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penelitian_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Penelitian',
                'verbose_name_plural': 'Penelitian',
                'ordering': ['-tahun_akademik'],
            },
        ),
        migrations.CreateModel(
            name='PKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(max_length=10)),
                ('kode_fakultas', models.CharField(max_length=10)),
                ('judul', models.TextField()),
                ('jml_mahasiswa', models.IntegerField(default=0)),
                ('jenis_hibah', models.CharField(blank=True, max_length=100, null=True)),
                ('sumber', models.CharField(blank=True, max_length=100, null=True)),
                ('durasi', models.IntegerField(default=1)),
                ('ln_i', models.CharField(blank=True, choices=[('L', 'Lokal'), ('N', 'Nasional'), ('I', 'Internasional')], max_length=5, null=True)),
                ('tahun_akademik', models.CharField(max_length=10)),
                ('pendanaan', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('link_bukti', models.URLField(blank=True, null=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pkm_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengabdian Masyarakat',
                'verbose_name_plural': 'Pengabdian Masyarakat',
                'ordering': ['-tahun_akademik'],
            },
        ),
        migrations.CreateModel(
            name='Publikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(max_length=10)),
                ('kode_fakultas', models.CharField(max_length=10)),
                ('judul', models.TextField()),
                ('jenis_publikasi', models.CharField(choices=[('IB', 'Internasional Bereputasi'), ('I', 'Internasional'), ('S1', 'Sinta 1'), ('S2', 'Sinta 2'), ('S3', 'Sinta 3'), ('S4', 'Sinta 4'), ('T', 'Tidak Terakreditasi')], max_length=5)),
                ('nama_jurnal', models.CharField(blank=True, max_length=200, null=True)),
                ('volume', models.CharField(blank=True, max_length=20, null=True)),
                ('nomor', models.CharField(blank=True, max_length=20, null=True)),
                ('halaman', models.CharField(blank=True, max_length=20, null=True)),
                ('tahun_terbit', models.IntegerField(blank=True, null=True)),
                ('tahun_akademik', models.CharField(max_length=10)),
                ('link_bukti', models.URLField(blank=True, null=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publikasi_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publikasi',
                'verbose_name_plural': 'Publikasi',
                'ordering': ['-tahun_akademik'],
            },
        ),
    ]
