# Generated by Django 6.0.4 on 2026-04-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinerja', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hki',
            options={'ordering': ['-tahun_akademik', 'semester'], 'verbose_name': 'HKI', 'verbose_name_plural': 'HKI'},
        ),
        migrations.AlterModelOptions(
            name='penelitian',
            options={'ordering': ['-tahun_akademik', 'semester'], 'verbose_name': 'Penelitian', 'verbose_name_plural': 'Penelitian'},
        ),
        migrations.AlterModelOptions(
            name='pkm',
            options={'ordering': ['-tahun_akademik', 'semester'], 'verbose_name': 'Pengabdian Masyarakat', 'verbose_name_plural': 'Pengabdian Masyarakat'},
        ),
        migrations.AlterModelOptions(
            name='publikasi',
            options={'ordering': ['-tahun_akademik', 'semester'], 'verbose_name': 'Publikasi', 'verbose_name_plural': 'Publikasi'},
        ),
        migrations.AddField(
            model_name='hki',
            name='semester',
            field=models.CharField(blank=True, choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap'), ('Keduanya', 'Keduanya')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='penelitian',
            name='semester',
            field=models.CharField(blank=True, choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap'), ('Keduanya', 'Keduanya')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pkm',
            name='semester',
            field=models.CharField(blank=True, choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap'), ('Keduanya', 'Keduanya')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='publikasi',
            name='semester',
            field=models.CharField(blank=True, choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap'), ('Keduanya', 'Keduanya')], max_length=10, null=True),
        ),
    ]
