# Generated by Django 6.0.4 on 2026-04-09 13:05

import django.db.models.deletion
import kinerja.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinerja', '0002_alter_hki_options_alter_penelitian_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BKD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(blank=True, max_length=10, null=True)),
                ('kode_fakultas', models.CharField(blank=True, max_length=10, null=True)),
                ('semester', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], max_length=10)),
                ('tahun_akademik', models.CharField(max_length=10)),
                ('file_bkd', models.FileField(blank=True, help_text='Upload file PDF BKD dari SISTER (max 5MB)', null=True, upload_to=kinerja.models.upload_bkd, validators=[kinerja.models.validate_bkd_file])),
                ('link_bkd', models.URLField(blank=True, help_text='Atau isi link Google Drive', null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bkd_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BKD',
                'verbose_name_plural': 'BKD',
                'ordering': ['-tahun_akademik', 'semester'],
                'unique_together': {('user', 'semester', 'tahun_akademik')},
            },
        ),
    ]
