# Generated by Django 6.0.4 on 2026-04-11 05:38

import django.db.models.deletion
import kinerja.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinerja', '0003_bkd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumenKinerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kinerja', models.CharField(choices=[('penelitian', 'Penelitian'), ('publikasi', 'Publikasi'), ('pkm', 'PKM'), ('hki', 'HKI'), ('bkd', 'BKD')], max_length=20)),
                ('kinerja_id', models.IntegerField()),
                ('jenis_dokumen', models.CharField(choices=[('surat_tugas', 'Surat Tugas'), ('kontrak', 'Kontrak/Perjanjian'), ('laporan_kemajuan', 'Laporan Kemajuan'), ('laporan_akhir', 'Laporan Akhir'), ('sertifikat', 'Sertifikat'), ('dokumentasi', 'Dokumentasi/Foto'), ('sk', 'SK/Keputusan'), ('lainnya', 'Lainnya')], max_length=20)),
                ('nama_dokumen', models.CharField(max_length=200)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('file_dokumen', models.FileField(blank=True, help_text='PDF/JPG/PNG max 5MB', null=True, upload_to=kinerja.models.upload_dokumen_kinerja)),
                ('link_dokumen', models.URLField(blank=True, null=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen_kinerja_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dokumen Kinerja',
                'verbose_name_plural': 'Dokumen Kinerja',
                'ordering': ['jenis_dokumen', 'nama_dokumen'],
            },
        ),
    ]
