# Generated by Django 6.0.4 on 2026-07-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinerja', '0004_dokumenkinerja'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BKD',
        ),
    ]
