# Generated by Django 6.0.4 on 2026-07-10 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinerja', '0005_delete_bkd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenkinerja',
            name='jenis_kinerja',
            field=models.CharField(choices=[('penelitian', 'Penelitian'), ('publikasi', 'Publikasi'), ('pkm', 'PKM'), ('hki', 'HKI'), ('bkd', 'BKD'), ('pengajaran', 'Pengajaran'), ('penghargaan', 'Penghargaan'), ('penunjang', 'Kegiatan Penunjang')], max_length=20),
        ),
        migrations.CreateModel(
            name='KegiatanPenunjang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(blank=True, max_length=10, null=True)),
                ('kode_fakultas', models.CharField(blank=True, max_length=10, null=True)),
                ('jenis_kegiatan', models.CharField(choices=[('reviewer', 'Reviewer Jurnal/Prosiding'), ('editor', 'Editor Jurnal'), ('narasumber', 'Narasumber/Pemateri'), ('panitia', 'Panitia Kegiatan'), ('organisasi_profesi', 'Pengurus Organisasi Profesi'), ('asesor', 'Asesor/Reviewer Akreditasi'), ('tim_adhoc', 'Tim Ad Hoc/Satgas'), ('lainnya', 'Lainnya')], max_length=25)),
                ('nama_kegiatan', models.CharField(max_length=200)),
                ('peran', models.CharField(blank=True, max_length=100, null=True)),
                ('penyelenggara', models.CharField(blank=True, max_length=150, null=True)),
                ('tingkat', models.CharField(blank=True, choices=[('L', 'Lokal'), ('N', 'Nasional'), ('I', 'Internasional')], max_length=5, null=True)),
                ('tanggal_mulai', models.DateField(blank=True, null=True)),
                ('tanggal_selesai', models.DateField(blank=True, null=True)),
                ('semester', models.CharField(blank=True, choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap'), ('Keduanya', 'Keduanya')], max_length=10, null=True)),
                ('tahun_akademik', models.CharField(max_length=10)),
                ('link_bukti', models.URLField(blank=True, null=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penunjang_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kegiatan Penunjang',
                'verbose_name_plural': 'Kegiatan Penunjang',
                'ordering': ['-tahun_akademik', 'semester'],
            },
        ),
        migrations.CreateModel(
            name='Pengajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(blank=True, max_length=10, null=True)),
                ('kode_fakultas', models.CharField(blank=True, max_length=10, null=True)),
                ('jenis_kegiatan', models.CharField(choices=[('mengajar', 'Mengajar Mata Kuliah'), ('membimbing_skripsi', 'Membimbing Skripsi/Tugas Akhir'), ('membimbing_tesis', 'Membimbing Tesis'), ('membimbing_disertasi', 'Membimbing Disertasi'), ('membimbing_pa', 'Pembimbing Akademik (PA)'), ('menguji', 'Menguji (Sidang/Komprehensif)'), ('lainnya', 'Lainnya')], max_length=25)),
                ('nama_kegiatan', models.CharField(help_text='Nama mata kuliah / nama mahasiswa dibimbing / jenis ujian', max_length=200)),
                ('sks', models.DecimalField(blank=True, decimal_places=1, help_text='Diisi untuk kegiatan Mengajar', max_digits=4, null=True)),
                ('jumlah_mahasiswa', models.IntegerField(default=0, help_text='Diisi untuk Membimbing/Menguji')),
                ('peran', models.CharField(blank=True, help_text='Contoh: Pembimbing 1, Ketua Penguji', max_length=100, null=True)),
                ('semester', models.CharField(blank=True, choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap'), ('Keduanya', 'Keduanya')], max_length=10, null=True)),
                ('tahun_akademik', models.CharField(max_length=10)),
                ('link_bukti', models.URLField(blank=True, null=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajaran_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengajaran',
                'verbose_name_plural': 'Pengajaran',
                'ordering': ['-tahun_akademik', 'semester'],
            },
        ),
        migrations.CreateModel(
            name='Penghargaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(blank=True, max_length=10, null=True)),
                ('kode_fakultas', models.CharField(blank=True, max_length=10, null=True)),
                ('nama_penghargaan', models.CharField(max_length=200)),
                ('lembaga_pemberi', models.CharField(blank=True, max_length=150, null=True)),
                ('tingkat', models.CharField(blank=True, choices=[('L', 'Lokal'), ('N', 'Nasional'), ('I', 'Internasional')], max_length=5, null=True)),
                ('tahun', models.IntegerField(blank=True, null=True)),
                ('semester', models.CharField(blank=True, choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap'), ('Keduanya', 'Keduanya')], max_length=10, null=True)),
                ('tahun_akademik', models.CharField(max_length=10)),
                ('link_bukti', models.URLField(blank=True, null=True)),
                ('tgl_input', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penghargaan_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Penghargaan',
                'verbose_name_plural': 'Penghargaan',
                'ordering': ['-tahun_akademik', 'semester'],
            },
        ),
    ]
