# Generated by Django 6.0.4 on 2026-07-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinerja', '0006_alter_dokumenkinerja_jenis_kinerja_kegiatanpenunjang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatanpenunjang',
            name='tingkat',
            field=models.CharField(blank=True, choices=[('L', 'Lokal'), ('R', 'Regional'), ('N', 'Nasional'), ('I', 'Internasional')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='penelitian',
            name='ln_i',
            field=models.CharField(blank=True, choices=[('L', 'Lokal'), ('R', 'Regional'), ('N', 'Nasional'), ('I', 'Internasional')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='penghargaan',
            name='tingkat',
            field=models.CharField(blank=True, choices=[('L', 'Lokal'), ('R', 'Regional'), ('N', 'Nasional'), ('I', 'Internasional')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pkm',
            name='ln_i',
            field=models.CharField(blank=True, choices=[('L', 'Lokal'), ('R', 'Regional'), ('N', 'Nasional'), ('I', 'Internasional')], max_length=5, null=True),
        ),
    ]
