# Generated by Django 6.0.4 on 2026-07-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinerja', '0007_alter_kegiatanpenunjang_tingkat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenkinerja',
            name='jenis_kinerja',
            field=models.CharField(choices=[('penelitian', 'Penelitian'), ('publikasi', 'Publikasi'), ('pkm', 'PKM'), ('hki', 'HKI'), ('bkd', 'BKD'), ('pengajaran', 'Pengajaran'), ('penghargaan', 'Penghargaan'), ('penunjang', 'Kegiatan Penunjang'), ('diklat', 'Diklat')], max_length=20),
        ),
    ]
