# Generated by Django 6.0.4 on 2026-07-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinerja', '0008_alter_dokumenkinerja_jenis_kinerja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenkinerja',
            name='jenis_kinerja',
            field=models.CharField(choices=[('penelitian', 'Penelitian'), ('publikasi', 'Publikasi'), ('pkm', 'PKM'), ('hki', 'HKI'), ('bkd', 'BKD'), ('pengajaran', 'Pengajaran'), ('penghargaan', 'Penghargaan'), ('penunjang', 'Kegiatan Penunjang'), ('diklat', 'Diklat'), ('sertifikasi', 'Sertifikasi'), ('tes', 'Tes')], max_length=20),
        ),
    ]
