# Generated by Django 5.1.15 on 2026-07-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinerja', '0009_alter_dokumenkinerja_jenis_kinerja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenkinerja',
            name='jenis_kinerja',
            field=models.CharField(choices=[('penelitian', 'Penelitian'), ('publikasi', 'Publikasi'), ('pkm', 'PKM'), ('hki', 'HKI'), ('bkd', 'BKD'), ('pengajaran', 'Pengajaran'), ('bimbingan_mahasiswa', 'Bimbingan Mahasiswa'), ('pengujian_mahasiswa', 'Pengujian Mahasiswa'), ('bahan_ajar', 'Bahan Ajar'), ('pembinaan_mahasiswa', 'Pembinaan Mahasiswa'), ('orasi_ilmiah', 'Orasi Ilmiah'), ('tugas_tambahan', 'Tugas Tambahan'), ('penghargaan', 'Penghargaan'), ('penunjang', 'Kegiatan Penunjang'), ('diklat', 'Diklat'), ('sertifikasi', 'Sertifikasi'), ('tes', 'Tes')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Pengajaran',
        ),
    ]
