# Generated by Django 5.1.15 on 2026-07-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinerja', '0010_alter_dokumenkinerja_jenis_kinerja_delete_pengajaran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penelitian',
            name='user',
        ),
        migrations.RemoveField(
            model_name='publikasi',
            name='user',
        ),
        migrations.DeleteModel(
            name='HKI',
        ),
        migrations.DeleteModel(
            name='Penelitian',
        ),
        migrations.DeleteModel(
            name='Publikasi',
        ),
    ]
