# Generated by Django 6.0.4 on 2026-07-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinerja', '0012_alter_dokumenkinerja_jenis_kinerja_delete_pkm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penghargaan',
            name='user',
        ),
        migrations.AlterField(
            model_name='dokumenkinerja',
            name='jenis_kinerja',
            field=models.CharField(choices=[('penelitian', 'Penelitian'), ('publikasi', 'Publikasi'), ('pkm', 'Pengabdian'), ('hki', 'HKI'), ('pembicara', 'Pembicara'), ('pengelola_jurnal', 'Pengelola Jurnal'), ('jabatan_struktural', 'Jabatan Struktural'), ('bkd', 'BKD'), ('pengajaran', 'Pengajaran'), ('bimbingan_mahasiswa', 'Bimbingan Mahasiswa'), ('pengujian_mahasiswa', 'Pengujian Mahasiswa'), ('bahan_ajar', 'Bahan Ajar'), ('pembinaan_mahasiswa', 'Pembinaan Mahasiswa'), ('orasi_ilmiah', 'Orasi Ilmiah'), ('tugas_tambahan', 'Tugas Tambahan'), ('anggota_profesi', 'Anggota Profesi'), ('penghargaan', 'Penghargaan'), ('penunjang', 'Kegiatan Penunjang'), ('diklat', 'Diklat'), ('sertifikasi', 'Sertifikasi'), ('tes', 'Tes')], max_length=20),
        ),
        migrations.DeleteModel(
            name='KegiatanPenunjang',
        ),
        migrations.DeleteModel(
            name='Penghargaan',
        ),
    ]
